// AUTOGENERATED FILE
// This file was generated from grammar.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface CustomQueryLanguageActionDict<T> extends BaseActionDict<T> {
  Program?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ProgramSequence?: (this: NonterminalNode, arg0: IterationNode) => T;
  StatementSequence?: (this: NonterminalNode, arg0: IterationNode) => T;
  Statement?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  SelectBlock?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode, arg4: TerminalNode, arg5: NonterminalNode, arg6: NonterminalNode, arg7: NonterminalNode, arg8: NonterminalNode) => T;
  SetStmt?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode) => T;
  AddStmt?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode) => T;
  UpsertStmt?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode) => T;
  RemoveStmt?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode, arg4: TerminalNode, arg5: NonterminalNode) => T;
  IdList?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Id?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  StringId?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
  IntId?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode) => T;
  PropPath?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: IterationNode) => T;
  PropName?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode, arg1: IterationNode) => T;
  jsonValue?: (this: NonterminalNode, arg0: IterationNode) => T;
  KwSelect?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  KwSet?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  KwAdd?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  KwUpsert?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  KwRemove?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  KwDone?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  identifierPart?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
  space?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
  comment?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  multiLineComment?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
  singleLineComment?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode) => T;
  nl?: (this: NonterminalNode, arg0: IterationNode, arg1: TerminalNode) => T;
  eol?: (this: NonterminalNode, arg0: NonterminalNode) => T;
}

export interface CustomQueryLanguageSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: CustomQueryLanguageActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: CustomQueryLanguageActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: CustomQueryLanguageActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: CustomQueryLanguageActionDict<T>): this;
}

export interface CustomQueryLanguageGrammar extends Grammar {
  createSemantics(): CustomQueryLanguageSemantics;
  extendSemantics(superSemantics: CustomQueryLanguageSemantics): CustomQueryLanguageSemantics;
}

declare const grammar: CustomQueryLanguageGrammar;
export default grammar;

