// AUTOGENERATED FILE
// This file was generated from grammar.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface CustomQueryLanguageActionDict<T> extends BaseActionDict<T> {
  Query?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  Statement?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  NestedBlock?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
  Target?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode, arg4: TerminalNode) => T;
  SetOp?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode) => T;
  AddOp?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  AddSetOp?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  RemoveOp?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode, arg4: TerminalNode) => T;
  path?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ident?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  idRaw?: (this: NonterminalNode, arg0: IterationNode) => T;
  jsonMock?: (this: NonterminalNode, arg0: IterationNode) => T;
  space?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
  comment_sql?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode) => T;
  comment_jsLine?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode) => T;
  comment_jsBlock?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
  comment?: (this: NonterminalNode, arg0: NonterminalNode) => T;
}

export interface CustomQueryLanguageSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: CustomQueryLanguageActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: CustomQueryLanguageActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: CustomQueryLanguageActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: CustomQueryLanguageActionDict<T>): this;
}

export interface CustomQueryLanguageGrammar extends Grammar {
  createSemantics(): CustomQueryLanguageSemantics;
  extendSemantics(superSemantics: CustomQueryLanguageSemantics): CustomQueryLanguageSemantics;
}

declare const grammar: CustomQueryLanguageGrammar;
export default grammar;

